/**
 * Maps suggested Figma Variable paths to CSS custom properties in `src/styles/tokens.css`.
 * Tokens Studio import: see `tokens-studio/tokens.json` (generated by `npm run tokens:studio`) and `tokens-studio/base.json`.
 * In Figma: Local variables → match `figmaPath` (slash groups); set values to the same hex/px as `:root`.
 *
 * Code Connect snippets (Vue + Element Plus):
 * - Themed controls: use EP props (`type="primary"`, `effect="light"`) — they read `--el-*`.
 * - Custom layout/type: use `var(--token-name)` in scoped `<style>` (see Admin/User/Login views).
 */
export const FIGMA_VARIABLE_CATALOG = [
  { figmaPath: 'color/surface/page', cssVar: '--color-surface-page' },
  { figmaPath: 'color/surface/auth', cssVar: '--color-surface-auth' },
  { figmaPath: 'color/surface/form', cssVar: '--color-surface-form' },
  { figmaPath: 'color/border/default', cssVar: '--color-border-default' },
  { figmaPath: 'color/border/subtle', cssVar: '--color-border-subtle' },
  { figmaPath: 'color/text/primary', cssVar: '--color-text-primary' },
  { figmaPath: 'color/text/secondary', cssVar: '--color-text-secondary' },
  { figmaPath: 'color/text/muted', cssVar: '--color-text-muted' },
  { figmaPath: 'color/accent', cssVar: '--color-accent' },
  { figmaPath: 'elevation/shadow/card', cssVar: '--shadow-card' },
  { figmaPath: 'radius/lg', cssVar: '--radius-lg' },
  { figmaPath: 'radius/md', cssVar: '--radius-md' },
  { figmaPath: 'space/1', cssVar: '--space-1' },
  { figmaPath: 'space/2', cssVar: '--space-2' },
  { figmaPath: 'space/3', cssVar: '--space-3' },
  { figmaPath: 'space/4', cssVar: '--space-4' },
  { figmaPath: 'space/5', cssVar: '--space-5' },
  { figmaPath: 'space/header', cssVar: '--space-header' },
  { figmaPath: 'font-size/brand-icon', cssVar: '--font-size-brand-icon' },
  { figmaPath: 'font-size/title-page', cssVar: '--font-size-title-page' },
  { figmaPath: 'font-size/section', cssVar: '--font-size-section' },
  { figmaPath: 'font-size/accent', cssVar: '--font-size-accent' },
  { figmaPath: 'font-weight/title', cssVar: '--font-weight-title' },
  { figmaPath: 'font-weight/semibold', cssVar: '--font-weight-semibold' },
  { figmaPath: 'letter-spacing/tight-title', cssVar: '--letter-spacing-tight-title' },
  { figmaPath: 'line-height/body', cssVar: '--line-height-body' },
  { figmaPath: 'layout/viewport-height', cssVar: '--layout-viewport-height' },
  { figmaPath: 'layout/login-card-width', cssVar: '--layout-login-card-width' },
  { figmaPath: 'layout/login-logo-max', cssVar: '--layout-login-logo-max' },
  { figmaPath: 'border-width/card', cssVar: '--border-width-card' },
  { figmaPath: 'section/accent-bar-width', cssVar: '--section-accent-bar-width' },
  { figmaPath: 'el/color/primary', cssVar: '--el-color-primary' },
  { figmaPath: 'el/color/primary-light-3', cssVar: '--el-color-primary-light-3' },
  { figmaPath: 'el/color/primary-light-5', cssVar: '--el-color-primary-light-5' },
  { figmaPath: 'el/color/primary-light-7', cssVar: '--el-color-primary-light-7' },
  { figmaPath: 'el/color/primary-light-8', cssVar: '--el-color-primary-light-8' },
  { figmaPath: 'el/color/primary-light-9', cssVar: '--el-color-primary-light-9' },
  { figmaPath: 'el/color/primary-dark-2', cssVar: '--el-color-primary-dark-2' }
] as const

/** Example strings for Code Connect docs (Vue SFC + Element Plus). */
export const CODE_CONNECT_TOKEN_SNIPPETS = {
  scopedColor: 'color: var(--color-text-primary);',
  scopedSpace: 'padding: var(--space-5);',
  elPrimaryButton: '<el-button type="primary">Label</el-button>',
  elPrimaryTag: '<el-tag type="primary" effect="light">Status</el-tag>'
} as const
