# Generated by Django 4.2.29 on 2026-07-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements_app', '0002_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementrequest',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirementrequest',
            name='impacted_users',
            field=models.CharField(blank=True, choices=[('<100', '<100'), ('100-500', '100-500'), ('500-1000', '500-1000'), ('>1000', '>1000')], max_length=10, null=True),
        ),
    ]
