# Generated by Django 4.2.29 on 2026-07-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements_app', '0003_requirementrequest_reject_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementrequest',
            name='estimated_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
