# Generated by Django 4.2.29 on 2026-07-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements_app', '0005_region_to_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementrequest',
            name='urgency',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
    ]
