# Generated by Django 4.2.30 on 2026-09-13 00:39

from django.db import migrations, models


def set_existing_admins_to_it(apps, schema_editor):
    CustomUser = apps.get_model('requirements_app', 'CustomUser')
    CustomUser.objects.filter(role='admin').update(department='it')


def unset_existing_admins_department(apps, schema_editor):
    CustomUser = apps.get_model('requirements_app', 'CustomUser')
    CustomUser.objects.filter(role='admin').update(department=None)


class Migration(migrations.Migration):

    dependencies = [
        ('requirements_app', '0006_requirementrequest_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('it', 'IT'), ('rnd', 'R&D')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='requirementrequest',
            name='owning_department',
            field=models.CharField(choices=[('it', 'IT'), ('rnd', 'R&D')], default='it', max_length=10),
        ),
        migrations.RunPython(set_existing_admins_to_it, unset_existing_admins_department),
    ]
