# Generated by Django 4.2.30 on 2026-09-15 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirements_app', '0007_customuser_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('create', 'Create'), ('edit', 'Edit')], max_length=10)),
                ('status', models.CharField(choices=[('asking', 'Asking'), ('generated', 'Generated'), ('confirmed', 'Confirmed'), ('discarded', 'Discarded')], default='asking', max_length=20)),
                ('form_context', models.JSONField(default=dict)),
                ('generated_description', models.TextField(blank=True, null=True)),
                ('generated_acceptance', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_sessions', to='requirements_app.requirementrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ai', 'AI'), ('user', 'User')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='requirements_app.reviewsession')),
            ],
        ),
    ]
